apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata: 
  name: azure-file-threescale
mountOptions: 

- uid=<CHANGE_ME>
- gid=0
- mfsymlinks
- cache=strict
parameters: 
  skuName: Premium_LRS
provisioner: file.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
